import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./_common/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-black text-white`}>
        <div className="flex h-full min-h-screen items-center justify-center">
          <div className="center min-h-screen w-[45rem] rounded p-[1vw]">
            <Provider>{children}</Provider>
          </div>
        </div>
      </body>
    </html>
  );
}
