import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./components/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-black text-white`}>
        <div className="flex items-center justify-center min-h-screen">
          <div className="p-[1vw] rounded center min-h-screen w-[45rem]">
            <Providers>{children}</Providers>
          </div>
        </div>
      </body>
    </html>
  );
}
